import {
  LayoutDashboard,
  BookOpen,
  ClipboardList,
  BarChart3,
  CalendarCheck,
  Calendar,
  MessageSquare,
  Users,
  TrendingUp,
  CreditCard,
  GraduationCap,
  FileText,
  Settings,
  FolderOpen,
  Megaphone,
  User,
  FileBarChart2,
  BookMarked,
  LayoutGrid,
  Send,
  Save,
  Check,
  X,
  Edit,
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  layoutDashboard: LayoutDashboard,
  bookOpen: BookOpen,
  clipboardList: ClipboardList,
  barChart3: BarChart3,
  calendarCheck: CalendarCheck,
  calendar: Calendar,
  messageSquare: MessageSquare,
  users: Users,
  trendingUp: TrendingUp,
  creditCard: CreditCard,
  graduationCap: GraduationCap,
  fileText: FileText,
  settings: Settings,
  folderOpen: FolderOpen,
  megaphone: Megaphone,
  user: User,
  fileBarChart2: FileBarChart2,
  bookMarked: BookMarked,
  layoutGrid: LayoutGrid,
  send: Send,
  save: Save,
  check: Check,
  x: X,
  edit: Edit,
};

export function getIcon(name: string) {
  return iconMap[name] || LayoutDashboard;
}
