import { useEffect, useState } from 'react';
import { Download, Filter, RefreshCw } from 'lucide-react';
import { PageHeader, DataTable, FilterPanel } from '@/features/admin';
import { adminApi } from '@/services/api/adminApi';
import type { AdminReport } from '@/types/admin';
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts';

const reportTypes = [
  { value: 'attendance', label: 'Attendance' },
  { value: 'grades', label: 'Grades' },
  { value: 'performance', label: 'Performance' },
  { value: 'enrollment', label: 'Enrollment' },
  { value: 'financial', label: 'Financial' },
  { value: 'custom', label: 'Custom' },
];

const chartData: Record<string, Array<Record<string, unknown>>> = {
  attendance: [
    { name: 'CS-A', present: 85, absent: 10, late: 5 },
    { name: 'CS-B', present: 78, absent: 15, late: 7 },
    { name: 'EC-A', present: 90, absent: 5, late: 5 },
    { name: 'ME-A', present: 82, absent: 12, late: 6 },
  ],
  grades: [
    { name: 'Mathematics', A: 45, B: 30, C: 15, D: 8, F: 2 },
    { name: 'Physics', A: 35, B: 40, C: 18, D: 5, F: 2 },
    { name: 'Chemistry', A: 40, B: 35, C: 20, D: 3, F: 2 },
    { name: 'Biology', A: 50, B: 30, C: 15, D: 4, F: 1 },
  ],
  performance: [
    { name: 'Semester 1', average: 78, passRate: 92 },
    { name: 'Semester 2', average: 82, passRate: 95 },
    { name: 'Semester 3', average: 75, passRate: 88 },
    { name: 'Semester 4', average: 80, passRate: 93 },
  ],
  enrollment: [
    { month: 'Jan', students: 120, parents: 110, faculty: 25 },
    { month: 'Feb', students: 135, parents: 125, faculty: 28 },
    { month: 'Mar', students: 148, parents: 138, faculty: 30 },
    { month: 'Apr', students: 160, parents: 150, faculty: 32 },
  ],
  financial: [
    { month: 'Jan', collected: 450000, pending: 50000 },
    { month: 'Feb', collected: 520000, pending: 45000 },
    { month: 'Mar', collected: 480000, pending: 60000 },
    { month: 'Apr', collected: 550000, pending: 40000 },
  ],
  custom: [
    { category: 'Category A', value: 400 },
    { category: 'Category B', value: 300 },
    { category: 'Category C', value: 200 },
    { category: 'Category D', value: 100 },
  ],
};

export function AdminReports() {
  const [reports, setReports] = useState<AdminReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState('attendance');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [showFilters, setShowFilters] = useState(false);

  useEffect(() => {
    async function loadReports() {
      setLoading(true);
      const data = await adminApi.getReports();
      setReports(data);
      setLoading(false);
    }
    loadReports();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    const report = await adminApi.generateReport(reportType, {
      dateFrom,
      dateTo,
    });
    setReports((prev) => [report, ...prev]);
    setGenerating(false);
  };

  const handleDownload = (report: AdminReport) => {
    const blob = new Blob([JSON.stringify(report.data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.type}-report.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const reportColumns = [
    {
      key: 'title',
      label: 'Title',
      render: (report: AdminReport) => (
        <span className="font-medium text-gray-900 dark:text-white">{report.title}</span>
      ),
    },
    {
      key: 'type',
      label: 'Type',
      render: (report: AdminReport) => (
        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300">
          {report.type}
        </span>
      ),
    },
    {
      key: 'period',
      label: 'Period',
      render: (report: AdminReport) => report.period,
    },
    {
      key: 'generatedAt',
      label: 'Generated At',
      render: (report: AdminReport) => report.generatedAt,
    },
    {
      key: 'generatedBy',
      label: 'Generated By',
      render: (report: AdminReport) => report.generatedBy,
    },
    {
      key: 'actions',
      label: 'Actions',
      render: (report: AdminReport) => (
        <button
          onClick={() => handleDownload(report)}
          className="inline-flex items-center gap-1 rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700 transition-colors"
        >
          <Download className="h-4 w-4" />
          Download
        </button>
      ),
      width: '120px',
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Reports" subtitle="Generate and manage reports" />

      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-end">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Report Type
              </label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white"
              >
                {reportTypes.map((type) => (
                  <option key={type.value} value={type.value}>
                    {type.label}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Date From
              </label>
              <input
                type="date"
                value={dateFrom}
                onChange={(e) => setDateFrom(e.target.value)}
                className="rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Date To
              </label>
              <input
                type="date"
                value={dateTo}
                onChange={(e) => setDateTo(e.target.value)}
                className="rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white"
              />
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`inline-flex items-center gap-2 rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium transition-colors ${showFilters ? 'bg-primary-50 border-primary-300 text-primary-700 dark:bg-primary-900/20 dark:border-primary-700 dark:text-primary-300' : 'text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700'}`}
            >
              <Filter className="h-4 w-4" />
              Filters
            </button>
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 font-medium bg-primary-600 text-white hover:bg-primary-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw className={`h-4 w-4 ${generating ? 'animate-spin' : ''}`} />
              {generating ? 'Generating...' : 'Generate Report'}
            </button>
          </div>
        </div>
        {showFilters && (
          <div className="mt-4">
            <FilterPanel
              open={showFilters}
              onClose={() => setShowFilters(false)}
              filters={{
                search: '',
                role: '',
                status: '',
                department: '',
                classId: '',
                dateFrom: '',
                dateTo: '',
                page: 1,
                pageSize: 10,
                sortBy: '',
                sortOrder: 'asc',
              }}
              onFilterChange={() => {}}
            />
          </div>
        )}
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 capitalize">
          {reportType} Report
        </h3>
        <div className="h-96">
          <ResponsiveContainer width="100%" height="100%">
            {reportType === 'attendance' && (
              <BarChart data={chartData.attendance}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Legend />
                <Bar dataKey="present" fill="#22c55e" name="Present" />
                <Bar dataKey="absent" fill="#ef4444" name="Absent" />
                <Bar dataKey="late" fill="#eab308" name="Late" />
              </BarChart>
            )}
            {reportType === 'grades' && (
              <BarChart data={chartData.grades}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Legend />
                <Bar dataKey="A" fill="#22c55e" name="A" />
                <Bar dataKey="B" fill="#3b82f6" name="B" />
                <Bar dataKey="C" fill="#eab308" name="C" />
                <Bar dataKey="D" fill="#f97316" name="D" />
                <Bar dataKey="F" fill="#ef4444" name="F" />
              </BarChart>
            )}
            {reportType === 'performance' && (
              <LineChart data={chartData.performance}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Legend />
                <Line type="monotone" dataKey="average" stroke="#3b82f6" name="Average Score" />
                <Line type="monotone" dataKey="passRate" stroke="#22c55e" name="Pass Rate %" />
              </LineChart>
            )}
            {reportType === 'enrollment' && (
              <AreaChart data={chartData.enrollment}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="month" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Legend />
                <Area
                  type="monotone"
                  dataKey="students"
                  stroke="#3b82f6"
                  fill="#93c5fd"
                  name="Students"
                />
                <Area
                  type="monotone"
                  dataKey="parents"
                  stroke="#22c55e"
                  fill="#86efac"
                  name="Parents"
                />
                <Area
                  type="monotone"
                  dataKey="faculty"
                  stroke="#a855f7"
                  fill="#d8b4fe"
                  name="Faculty"
                />
              </AreaChart>
            )}
            {reportType === 'financial' && (
              <AreaChart data={chartData.financial}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="month" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Legend />
                <Area
                  type="monotone"
                  dataKey="collected"
                  stroke="#22c55e"
                  fill="#86efac"
                  name="Collected"
                />
                <Area
                  type="monotone"
                  dataKey="pending"
                  stroke="#ef4444"
                  fill="#fca5a5"
                  name="Pending"
                />
              </AreaChart>
            )}
            {reportType === 'custom' && (
              <BarChart data={chartData.custom}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="category" />
                <YAxis />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#1f2937',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#fff',
                  }}
                />
                <Bar dataKey="value" fill="#3b82f6" name="Value" />
              </BarChart>
            )}
          </ResponsiveContainer>
        </div>
      </div>

      <div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Report History</h3>
        <DataTable
          data={reports}
          columns={reportColumns}
          getRowId={(report) => report.id}
          loading={loading}
          emptyMessage="No reports generated yet"
        />
      </div>
    </div>
  );
}
